[package]
name = "ftp_core_python"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]  # Pour PyO3

[dependencies]
ftp_core = { path = "../ftp_core" }
pyo3 = { version = "0.26.0", features = ["extension-module"] }


