site_name: FTP Calculator Documentation
site_description: Documentation unifiée pour FTP Core, Python Library et Excel Add-in
site_url: https://ce-teuf.github.io/FTP_CALCULATOR
repo_url: https://github.com/ce-teuf/FTP_CALCULATOR/
repo_name: ce-teuf/FTP_CALCULATOR

nav:
  - Accueil: index.md
  - FTP Core:
      - Présentation: ftp_core.md
      - API Reference: api/ftp_core/
  - Python Library:
      - Installation: ftp_core_python.md
      - Utilisation: python_examples.md
  - Excel Add-in:
      - Installation: ftp_core_excel.md
      - Guide: excel_guide.md
  - Exemples: examples/index.md

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.suggest
    - search.highlight

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [../ftp_core_python/src]
        rust:
          paths: [../ftp_core/src]

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - toc:
      permalink: true