name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test-core:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        run: rustup update stable && rustup default stable
      - name: Test ftp_core
        run: cd crates/ftp_core && cargo test.yml --verbose

  build-excel:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        run: rustup update stable && rustup default stable
      - name: Build C bindings for Excel
        run: cd crates/ftp_core_bindings_c && cargo build --release
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ftp_core_bindings_c-dll
          path: crates/ftp_core_bindings_c/target/release/ftp_core_bindings_c.dll

  build-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        run: rustup update stable && rustup default stable
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install maturin
        run: pip install maturin
      - name: Build Python wheel
        run: cd crates/ftp_core_bindings_pyo3 && maturin build --release
        env:
          MATURIN_PYTHON: python3.13
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-wheel
          path: crates/ftp_core_bindings_pyo3/target/wheels/*.whl

  check-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check formatting
        run: cargo fmt --all -- --check

  check-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust and clippy
        run: |
          rustup update stable && rustup default stable
          rustup component add clippy  # <-- Add this line
      - name: Run clippy
        run: cargo clippy --workspace -- -D warnings