name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        working-directory: ./  # All commands will run from the 'docs' folder
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          pip install --upgrade mkdocs mkdocs-material ghp-import mkdocstrings mkdocstrings-python mkdocs-mermaid2-plugin

      - name: Build documentation
        run: mkdocs build --clean

      - name: Deploy to GitHub Pages
        run: ghp-import -n -p -f site/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
