name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

# Grant GITHUB_TOKEN the permissions required to make a Pages deployment
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          pip install --upgrade mkdocs mkdocs-material ghp-import mkdocstrings mkdocstrings-python mkdocs-mermaid2-plugin

      - name: Build documentation
        run: |
          cd docs
          mkdocs build --clean --config-file ./mkdocs.yml

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: docs/site/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2